### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Chydzim** [pahimar/Equivalent-Exchange-3#1061]
Game is crashing after install ee3.

Singleplayer:

```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 27.05.16 22:35
Description: Initializing game

java.lang.NoSuchFieldError: clay
	at com.pahimar.ee3.block.BlockChalk.<init>(BlockChalk.java:14)
	at com.pahimar.ee3.init.ModBlocks.<clinit>(ModBlocks.java:14)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:70)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:39)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:554)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at info.mineshafter.GameStarter.main(GameStarter.java:24)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.pahimar.ee3.block.BlockChalk.<init>(BlockChalk.java:14)
	at com.pahimar.ee3.init.ModBlocks.<clinit>(ModBlocks.java:14)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:70)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:39)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:554)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at info.mineshafter.GameStarter.main(GameStarter.java:24)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 342518568 bytes (326 MB) / 1365245952 bytes (1302 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 85 mods loaded, 78 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UC	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UC	da3dsoulASMFix{0.1.0} [DA3DSOUL ASM Fixes] (minecraft.jar) 
	UC	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UC	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UC	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UC	NotEnoughItems{1.0.5.120} [Not Enough Items] (Not-Enough-Items-1.7.10-Latest.jar) 
	UC	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UC	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UC	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UC	gregapi{GT6-MC1710} [Greg-API] (gregtech_1.7.10-6.02.06.jar) 
	UC	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
	UC	BuildCraft|Core{7.1.16} [BuildCraft] (buildcraft-7.1.16.jar) 
	UC	BuildCraft|Builders{7.1.16} [BC Builders] (buildcraft-7.1.16.jar) 
	UC	BuildCraft|Transport{7.1.16} [BC Transport] (buildcraft-7.1.16.jar) 
	UC	BuildCraft|Energy{7.1.16} [BC Energy] (buildcraft-7.1.16.jar) 
	UC	BuildCraft|Silicon{7.1.16} [BC Silicon] (buildcraft-7.1.16.jar) 
	UC	BuildCraft|Factory{7.1.16} [BC Factory] (buildcraft-7.1.16.jar) 
	UC	IC2{2.2.822-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.822-experimental.jar) 
	UC	ImmibisCore{59.1.4} [Immibis Core] (immibis-core-59.1.4.jar) 
	UC	LiquidXP{59.0.2} [Liquid XP] (liquid-xp-59.0.2.jar) 
	UC	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UC	ThermalFoundation{1.7.10R1.2.4} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.4-114.jar) 
	UC	ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.2-240.jar) 
	UC	Additional-Buildcraft-Objects{MC1.7.10-BC7.1release4.0.9} [Additional Buildcraft Objects] (ABO-MC1.7.10-BC7.1release4.0.9.jar) 
	UC	BuildCraft|Robotics{7.1.16} [BC Robotics] (buildcraft-7.1.16.jar) 
	UC	Forestry{4.2.12.60} [Forestry for Minecraft] (forestry_1.7.10-4.2.12.60.jar) 
	UC	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5 (1).jar) 
	UC	LogisticsPipes{0.9.3.122} [Logistics Pipes] (logisticspipes-0.9.3.122.jar) 
	UC	additionalpipes{4.7.0} [Additional Pipes] (additionalpipes-4.7.2.jar) 
	UC	AdvancedMachines{1.1.6} [IC2 Advanced Machines Addon] (AdvancedMachinesAS-1.7.10.jar) 
	UC	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) 
	UC	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UC	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UC	ae2stuff{0.5.0.56} [AE2 Stuff] (ae2stuff-0.5.0.56-mc1.7.10.jar) 
	UC	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UC	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (cfm-3.4.8-mc1.7.10.jar) 
	UC	CompactSolars{4.4.37.314} [Compact Solar Arrays] (CompactSolars-1.7.10-4.4.37.314-universal.jar) 
	UC	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) 
	UC	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UC	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UC	thebombzenapi{2.4.2} [ThebombzenAPI] (ThebombzenAPI-v2.4.2-mc1.7.10.jar) 
	UC	enchantview{4.1.0} [EnchantView] (EnchantView-v4.1.0-mc1.7.10.jar) 
	UC	EE3{0.3.0.536} [Equivalent Exchange 3] (EquivalentExchange3-1.7.10-0.3.0.536-dev.jar) 
	UC	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.460.jar) 
	UC	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.460.jar) 
	UC	gravestonemod{1.7.10} [Gravestones] (GraveStones 1.7.10 -3.jar) 
	UC	IC2NuclearControl{2.4.0a} [Nuclear Control 2] (IC2NuclearControl-2.4.0a.jar) 
	UC	MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UC	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UC	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UC	gregapi_post{GT6-MC1710} [Greg-API-Post] (gregtech_1.7.10-6.02.06.jar) 
	UC	gregtech{GT6-MC1710} [GregTech] (gregtech_1.7.10-6.02.06.jar) 
	UC	IC2CA{1.14.5.06} [IndustrialCraft 2 Combo Armors] (ic2ca-1.7.10-1.14.5.06.jar) 
	UC	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
	UC	InGameInfoXML{2.8.1.82} [InGame Info XML] (InGameInfoXML-1.7.10-2.8.1.82-universal (1).jar) 
	UC	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (Inventory-Tweaks-Mod-1.7.10.jar) 
	UC	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UC	JABBA{1.2.2} [JABBA] (Jabba-1.2.2_1.7.10.jar) 
	UC	mam{1.7.10-1.0.2} [Myths & Monsters Mod] (mam-1.7.10-1.0.2.jar) 
	UC	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UC	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) 
	UC	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UC	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar) 
	UC	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UC	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UC	MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UC	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UC	MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UC	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UC	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UC	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UC	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UC	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UC	MorePlanet{1.3.1} [More Planets] (More-Planets-1.7.10-1.3.1.jar) 
	UC	Mystcraft{0.12.3.02} [Mystcraft] (mystcraft-1.7.10-0.12.3.02.jar) 
	UC	NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22.jar) 
	UD	MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.22' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	CoFHCore: -[1.7.10]3.1.2-325
	ThermalFoundation: -[1.7.10]1.2.4-114
	ThermalExpansion: -[1.7.10]4.1.2-240
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	MineFactoryReloaded: -[1.7.10]2.8.1-174
	Mantle Environment: Environment healthy.
	TConstruct Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: gregtech
	NetherOres: -[1.7.10]2.3.1-22
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.22, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: Polski (Polska)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```

Server:

```
[22:48:14] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchFieldError: maxStackSize
        at com.pahimar.ee3.item.ItemEE.<init>(ItemEE.java:16) ~[ItemEE.class:?]
        at com.pahimar.ee3.item.ItemAlchemicalBag.<init>(ItemAlchemicalBag.java:
36) ~[ItemAlchemicalBag.class:?]
        at com.pahimar.ee3.init.ModItems.<clinit>(ModItems.java:11) ~[ModItems.c
lass:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_91]
        at cpw.mods.fml.common.registry.ObjectHolderRegistry.scanTarget(ObjectHo
lderRegistry.java:70) ~[ObjectHolderRegistry.class:?]
        at cpw.mods.fml.common.registry.ObjectHolderRegistry.findObjectHolders(O
bjectHolderRegistry.java:39) ~[ObjectHolderRegistry.class:?]
        at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:554) ~[Loade
r.class:?]
        at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHand
ler.java:88) ~[FMLServerHandler.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.j
ava:314) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(Dedicated
Server.java:117) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [M
inecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[li.class:?]
[22:48:14] [Server thread/ERROR]: This crash report has been saved to: C:\Users\
Daniel\Desktop\Serwer\Mody\.\crash-reports\crash-2016-05-27_22.48.14-server.txt
[22:48:14] [Server thread/WARN] [FML]: Can't revert to frozen GameData state wit
hout freezing first.
[22:48:14] [Server thread/INFO] [FML]: Applying holder lookups
[22:48:14] [Server thread/INFO] [FML]: Holder lookups applied
[22:48:15] [Server thread/INFO] [FML]: The state engine was in incorrect state I
NITIALIZATION and forced into state SERVER_STOPPED. Errors may have been discard
ed.
Press any key to continue . . .
```

**Comment by pahimar** [comment]
This crash makes no sense to me. No such field 'clay' in BlockChalk? No 'maxStackSize' in ItemAlchemicalBag?

I suspect you have a coremod that's doing wonky things

**Comment by Chydzim** [comment]
Here is my modpack: https://mega.nz/#!FwV2kYpQ!ouTGhh7ZRVhijDhZZ2mrGVK1Uhcmm5l3auNnr1x37fY

if u want, u can check which mod is causing crash.

When i run minecraft with these mods, i have additional mod called "DA3DSOUL ASM FIX" with description "I hack other people's mods! Baka!". Do you know what is this? '_'

**Comment by tahg** [comment]
You are using Mineshafter to avoid paying for the game.  I believe I speak for most modders when I say we do NOT condone this, and won't provide any technical support for users who use these types of hacks.  If you decide to use the stock Forge and Minecraft jars to play the game, then by all means let us know if you have issues.

**Comment by pahimar** [comment]
Yeah, for one I won't support someone running hacks to avoid paying for the game

Two, you are running mods that are likely hacking how other mods work. I can guarantee that this crash you are seeing has nothing to do with my code (you can look at the classes in question from the crash report in this repo).

You could try, yourself, removing the mods in question and seeing what happens but at this point this is not a crash I can help you with. Sorry.
