### ISSUE TITLE
Crash while pushing "V" while holding chalk

### ISSUE THREAD

**Issue by Unknown-88** [pahimar/Equivalent-Exchange-3#838]
There is nothing else bound to V, only occurs in single player;

[17:31:08] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel ee3
java.lang.NullPointerException
	at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$7.selectNetworks(FMLOutboundHandler.java:193) ~[FMLOutboundHandler$OutboundTarget$7.class:?]
	at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273) ~[FMLOutboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115) ~[MessageToMessageEncoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:210) ~[SimpleNetworkWrapper.class:?]
	at com.pahimar.ee3.tileentity.TileEntityAludel.func_70296_d(TileEntityAludel.java:313) ~[TileEntityAludel.class:?]
	at net.minecraft.inventory.Slot.func_75218_e(Slot.java:83) ~[aay.class:?]
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:78) ~[aay.class:?]
	at net.minecraft.inventory.Container.func_75131_a(SourceFile:390) ~[zs.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147241_a(NetHandlerPlayClient.java:1057) ~[bjb.class:?]
	at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:49) ~[go.class:?]
	at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:11) ~[go.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) ~[bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) ~[1.7.10.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.11.jar:?]

**Comment by pahimar** [comment]
This is not related to Chalk. You have a corrupted Aludel base block somewhere in your world

Proof:
In your logs;
com.pahimar.ee3.tileentity.TileEntityAludel.func_70296_d(TileEntityAludel.java:313)

That's the markDirty method in TileEntityAludel;
https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/tileentity/TileEntityAludel.java#L313-313

Try this again with a new world

**Comment by Unknown-88** [comment]
Unable to reproduce, weird, wonder how that happened
