### ISSUE TITLE
Crash during loading with most recent Electrical Age mod installed

### ISSUE THREAD

**Issue by Arrabal-** [pahimar/Equivalent-Exchange-3#917]
Forge locks up during the post init phase for EE3 and does not produce a crash report.  I have confirmed that this is due to something that is happening in the Electrical Age mod (version 1.9_r46 worked fine, but both 1.10_r47 and 1.10_r48 cause this crash to happen).  I have copied the relevant sections of the FML log below for reference and have included a pastebin for the full log--please note that the log file ends abruptly because Forge locks up and I have to force quite to exit.  Looks to me like it has something to do with how Electrical Age is registering one or more of their recipes, but I didn't see anything obvious in the code.  I will also post this issue to the Electrical Age issue log.

FML log section:
[00:55:12] [Client thread/ERROR] [FML/]: Caught exception from EE3
java.util.UnknownFormatConversionException: Conversion = '@'
	at java.util.Formatter.checkText(Formatter.java:2579) ~[?:1.8.0_25]
	at java.util.Formatter.parse(Formatter.java:2565) ~[?:1.8.0_25]
	at java.util.Formatter.format(Formatter.java:2501) ~[?:1.8.0_25]
	at java.util.Formatter.format(Formatter.java:2455) ~[?:1.8.0_25]
	at java.lang.String.format(String.java:2927) ~[?:1.8.0_25]
	at cpw.mods.fml.relauncher.FMLRelaunchLog.log(FMLRelaunchLog.java:60) [forge-1.7.10-10.13.4.1451-1.7.10.jar:?]
	at cpw.mods.fml.common.FMLLog.log(FMLLog.java:25) [FMLLog.class:?]
	at com.pahimar.ee3.util.LogHelper.log(LogHelper.java:11) ~[LogHelper.class:?]
	at com.pahimar.ee3.util.LogHelper.trace(LogHelper.java:46) ~[LogHelper.class:?]
	at com.pahimar.ee3.recipe.RecipeRegistry.addRecipe(RecipeRegistry.java:65) ~[RecipeRegistry.class:?]
	at com.pahimar.ee3.api.exchange.RecipeRegistryProxy.addRecipe(RecipeRegistryProxy.java:17) ~[RecipeRegistryProxy.class:?]
	at com.pahimar.ee3.recipe.RecipesVanilla.registerRecipes(RecipesVanilla.java:40) ~[RecipesVanilla.class:?]
	at com.pahimar.ee3.recipe.RecipeRegistry.registerVanillaRecipes(RecipeRegistry.java:72) ~[RecipeRegistry.class:?]
	at com.pahimar.ee3.EquivalentExchange3.postInit(EquivalentExchange3.java:116) ~[EquivalentExchange3.class:?]

Here is a pastebin of just the ELN recipe registrations during the EE3 post init phase:  http://pastebin.com/wDRRM941

Pastebins of FML Log:
part 1: http://pastebin.com/j6Lu0Jw0
part 2: http://pastebin.com/N7apLkGV
part 3: http://pastebin.com/6AVp9Esn
part 4 (start of EE3 post init): http://pastebin.com/yaAa4P3E
part 5: http://pastebin.com/0r60MBS8
part 6: http://pastebin.com/nxUhtTdB
part 7: http://pastebin.com/ANgSy1ht
part 8 (end of EE3 post init): http://pastebin.com/WPFi8h45
part 9:  http://pastebin.com/Zvwy1eiZ

**Comment by Arrabal-** [comment]
Fixed in next release of Electrical Age.  Issue was due to an item having the '%' character in the name.
