### ISSUE TITLE
Crash out of server with Reactorcraft/Dependencies

### ISSUE THREAD

**Issue by MrFata** [pahimar/Equivalent-Exchange-3#967]
Exception caught during firing event cpw.mods.fml.common.gameevent.PlayerEvent$PlayerLoggedInEvent@7a0773d1:
java.lang.NullPointerException
at com.pahimar.ee3.exchange.EnergyValueRegistry.serialize(EnergyValueRegistry.java:819) ~[EnergyValueRegistry.class:?]
at com.pahimar.ee3.exchange.EnergyValueRegistry.serialize(EnergyValueRegistry.java:27) ~[EnergyValueRegistry.class:?]
at com.google.gson.TreeTypeAdapter.write(TreeTypeAdapter.java:70) ~[TreeTypeAdapter.class:?]
at com.google.gson.Gson.toJson(Gson.java:593) ~[Gson.class:?]
at com.google.gson.Gson.toJson(Gson.java:572) ~[Gson.class:?]
at com.google.gson.Gson.toJson(Gson.java:527) ~[Gson.class:?]
at com.google.gson.Gson.toJson(Gson.java:507) ~[Gson.class:?]
at com.pahimar.ee3.exchange.EnergyValueRegistry.toJson(EnergyValueRegistry.java:781) ~[EnergyValueRegistry.class:?]
at com.pahimar.ee3.network.message.MessageSyncEnergyValues.<init>(MessageSyncEnergyValues.java:30) ~[MessageSyncEnergyValues.class:?]
at com.pahimar.ee3.handler.PlayerEventHandler.onPlayerLoggedIn(PlayerEventHandler.java:50) ~[PlayerEventHandler.class:?]
at cpw.mods.fml.common.eventhandler.ASMEventHandler_652_PlayerEventHandler_onPlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:550) [FMLCommonHandler.class:?]
at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:180) [oi.class:?]
at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190) [NetworkDispatcher.class:?]
at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:463) [NetworkDispatcher.class:?]
at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:17) [HandshakeCompletionHandler.class:?]
at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) [HandshakeCompletionHandler.class:?]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #990
